import {
  FaPaintBrush,
  FaCode,
  FaBriefcase,
  FaPenFancy,
  FaFlag,
  FaFileAlt,
  FaUsers,
  FaStar,
  FaTrophy,
  FaMedal,
  FaCertificate,
  FaHandshake,
  FaBullhorn,
  FaNetworkWired,
  FaLinkedin,
  FaInstagram,
  FaFacebook,
  FaTwitter,
  FaYoutube,
  FaWhatsapp,
  FaEnvelope,
  FaBook,
  FaCalendar,
  FaMapMarkerAlt,
  FaSearchPlus,
  FaPlayCircle,
  FaCog,
  FaTimes,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaGlobe,
  FaExternalLinkAlt,
} from 'react-icons/fa';

const iconMap = {
  FaPaintBrush,
  FaCode,
  FaBriefcase,
  FaPenFancy,
  FaFlag,
  FaFileAlt,
  FaUsers,
  FaStar,
  FaTrophy,
  FaMedal,
  FaCertificate,
  FaHandshake,
  FaBullhorn,
  FaNetworkWired,
  FaLinkedin,
  FaInstagram,
  FaFacebook,
  FaTwitter,
  FaYoutube,
  FaWhatsapp,
  FaEnvelope,
  FaBook,
  FaCalendar,
  FaMapMarkerAlt,
  FaSearchPlus,
  FaPlayCircle,
  FaCog,
  FaTimes,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaGlobe,
  FaExternalLinkAlt,
};

export const getIcon = (iconName, className = '') => {
  const IconComponent = iconMap[iconName];
  return IconComponent ? <IconComponent className={className} /> : null;
};
